# Generated by Django 4.2.17 on 2025-01-22 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_companies',
            fields=[
                ('client_company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'client_companies',
            },
        ),
        migrations.CreateModel(
            name='Client_members',
            fields=[
                ('client_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=150)),
                ('client_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[projects.models.validate_phone_number])),
                ('client_company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_member', to='projects.client_companies')),
            ],
            options={
                'db_table': 'client_members',
            },
        ),
        migrations.CreateModel(
            name='geographies',
            fields=[
                ('geography_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'geographies',
            },
        ),
        migrations.CreateModel(
            name='Published_statuses',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'published_statuses',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('timeline_start', models.DateField()),
                ('timeline_end', models.DateField()),
                ('expected_calls', models.IntegerField()),
                ('completed_calls', models.IntegerField(default=0)),
                ('general_screening_questions', models.TextField(null=True)),
                ('client_requirements', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.client_companies')),
                ('geography_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.geographies')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Project_published',
            fields=[
                ('project_publish_id', models.AutoField(primary_key=True, serialize=False)),
                ('angles', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_publish', to='experts.experts')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_publish', to='projects.projects')),
                ('status_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_publish', to='projects.published_statuses')),
            ],
            options={
                'db_table': 'project_published',
            },
        ),
        migrations.CreateModel(
            name='Project_pipelines',
            fields=[
                ('project_pipeline_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_pipeline', to='experts.experts')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_pipeline', to='projects.projects')),
            ],
            options={
                'db_table': 'project_pipelines',
            },
        ),
        migrations.CreateModel(
            name='Project_files',
            fields=[
                ('projectFile_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('word', 'Word')], max_length=50)),
                ('file_path', models.FileField(upload_to='project_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='projects.projects')),
            ],
            options={
                'db_table': 'project_files',
            },
        ),
        migrations.CreateModel(
            name='companiesOfInterest',
            fields=[
                ('company_of_interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150)),
                ('is_past', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=False)),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyOfInterest', to='projects.projects')),
            ],
            options={
                'db_table': 'companies_of_interest',
            },
        ),
        migrations.CreateModel(
            name='Client_teams',
            fields=[
                ('client_team_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_team', to='projects.client_members')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_team', to='projects.projects')),
            ],
            options={
                'db_table': 'client_teams',
            },
        ),
    ]
