# Generated by Django 5.1.5 on 2025-02-09 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_with_experts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project_pipelines',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_pipeline', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project_published',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_publish', to=settings.AUTH_USER_MODEL),
        ),
    ]
