# Generated by Django 4.2.18 on 2025-02-28 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
        ('projects', '0003_project_pipelines_user_id_project_published_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='general_screening_questions',
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screeningQuestion', to='projects.projects')),
            ],
            options={
                'db_table': 'screening_questions',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('expert_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionAnswer', to='experts.experts')),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionAnswer', to='projects.questions')),
            ],
            options={
                'db_table': 'answers',
            },
        ),
    ]
