# Generated by Django 4.2.18 on 2025-04-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_projects_general_screening_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_published',
            name='expert_availability',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
