from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter
from .views import UserViewSet
from .views import LoginView
from .views import LoginView, LogoutView, CSRFTokenView


# Create a router
router = DefaultRouter()
# Register the UserViewSet with a route
router.register('users', UserViewSet)

urlpatterns = [
    #path('login/', views.users, name='users'), #url for testing purpose, print hello world
    path('', include(router.urls)),  # Includes all routes generated by the router (/users)
    path('api/login/', LoginView.as_view(), name='api_login'),
    path("api/csrf/", CSRFTokenView.as_view(), name="api_csrf"),  # Endpoint untuk mengambil CSRF token

]