# Generated by Django 4.2.17 on 2025-01-22 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import experts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('expert_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('linkedIn_profile_link', models.CharField(max_length=255, null=True)),
                ('industry', models.CharField(max_length=200)),
                ('country_of_residence', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('expert_cost', models.PositiveIntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[experts.models.validate_phone_number])),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'experts',
            },
        ),
        migrations.CreateModel(
            name='ExpertExperiences',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='experts.experts')),
            ],
            options={
                'db_table': 'experiences',
            },
        ),
    ]
