from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter
from .views import ExpertViewSet
from .views import ExperienceViewSet

# Create a router
router = DefaultRouter()
# Register the ExpertViewSet with a route
router.register('experts', ExpertViewSet)
router.register('expert_experiences', ExperienceViewSet)

urlpatterns = [
    path('', include(router.urls)),  # Includes all routes generated by the router
]