from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter
from .views import ProjectViewSet
from .views import ClientCompaniesViewSet
from .views import ClientMembersViewSet
from .views import ClientTeamsViewSet
from .views import GeographiesViewSet
from .views import ProjectFilesViewSet
from .views import ProjectPipelinesViewSet
from .views import ProjectPublishedViewSet
from .views import ProjectExpertsViewSet


# Create a router
router = DefaultRouter()
# Register the ProjectViewSet with a route
router.register('projects', ProjectViewSet)
router.register('project_client_company', ClientCompaniesViewSet)
router.register('client_members', ClientMembersViewSet)
router.register('project_client_team', ClientTeamsViewSet)
router.register('projects_geography', GeographiesViewSet)
router.register('projects_files', ProjectFilesViewSet)
router.register('project_pipeline', ProjectPipelinesViewSet)
router.register('project_published', ProjectPublishedViewSet)
router.register('project_experts', ProjectExpertsViewSet)

urlpatterns = [
    path('', include(router.urls)),  # Includes all routes generated by the router (/projects)
]